# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ManyToManyField(to='plateup.User'),
        ),
    ]
