# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateup', '0002_auto_20160331_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('N/A', 'not defined')], default='not defined', max_length=15),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateup.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateup.User'),
        ),
    ]
