# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateup', '0003_auto_20160404_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
