# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateup', '0004_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantuser',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantuser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='plateup.Restaurant'),
        ),
        migrations.DeleteModel(
            name='RestaurantUser',
        ),
    ]
